// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjsmz5pDSMAgoTZX1gKeomyhAB9uPSb84',
    appId: '1:569231134607:web:000efcd24134367d0e85fa',
    messagingSenderId: '569231134607',
    projectId: 'attendance-90579',
    authDomain: 'attendance-90579.firebaseapp.com',
    storageBucket: 'attendance-90579.appspot.com',
    measurementId: 'G-QJH3QHX6ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJxE9CCAKfKaGvMcdBSeRBOEfI5Wo54xs',
    appId: '1:569231134607:android:9b1b43f15edf6c040e85fa',
    messagingSenderId: '569231134607',
    projectId: 'attendance-90579',
    storageBucket: 'attendance-90579.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy6-Vedxo2TqmLIxL2CCiEUH6Jx6JJkMI',
    appId: '1:569231134607:ios:7053e6013f3ee3320e85fa',
    messagingSenderId: '569231134607',
    projectId: 'attendance-90579',
    storageBucket: 'attendance-90579.appspot.com',
    iosBundleId: 'com.application.muhammadiyah.muhammadiyah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy6-Vedxo2TqmLIxL2CCiEUH6Jx6JJkMI',
    appId: '1:569231134607:ios:4d8363cc99b3491e0e85fa',
    messagingSenderId: '569231134607',
    projectId: 'attendance-90579',
    storageBucket: 'attendance-90579.appspot.com',
    iosBundleId: 'com.application.muhammadiyah.muhammadiyah.RunnerTests',
  );
}
